import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
    appearance={{
      layout: {
        logoImageUrl: "/icons/connect.png",
      },
      variables: {
        colorPrimary: "#3700B3",
        colorBackground: "#CCCCFF",
        colorInputBackground: "#99f",
      },
    }}
    >
      <html lang="en">
        <body className={`${inter.className} bg-dark-2 `}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
